name: epub_view
description: Flutter widget for view EPUB documents on on Web, MacOs, Android and iOS. Based on dart-epub package.
version: 1.1.0
homepage: https://github.com/rbcprolabs/packages.flutter/tree/master/packages/epub_view

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.17.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  epub: ^2.1.0
  equatable: ^1.2.3
  html: ^0.14.0+3
  flutter_html: ^1.0.0
  scrollable_positioned_list: ^0.1.7
  rxdart: ^0.24.1

dependency_overrides:
  # flutter_html usages flutter_svg, DiagnosticableMixin problem
  flutter_svg: ^0.19.0
  # epub depends on 2.6.0
  xml: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

